### ISSUE TITLE
Problems running the sample application (Android)

### ISSUE THREAD

**Issue by Rart3001** [card-io/react-native-card-io#1] opened 2016-09-12 14:04 UTC
When he tried to run the sample application by following the specified step shows the following error:

```
D/CardIOActivity(15657): onActivityResult(requestCode:10, resultCode:13274384, ...
V/CardIOActivity(15657): EXTRA_SCAN_RESULT: {Visa: •••• •••• •••• 3341  expiry:2/2018}
D/SensorManager(  893): enableSensor native: LIS3DSH Accelerometer
D/AndroidRuntime(15657): Shutting down VM
E/AndroidRuntime(15657): FATAL EXCEPTION: main
E/AndroidRuntime(15657): Process: com.awesomeproject, PID: 15657
E/AndroidRuntime(15657): java.lang.AbstractMethodError: abstract method "void   com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int,   android.content.Intent)"
E/AndroidRuntime(15657):    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:210)
E/AndroidRuntime(15657):    at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:612)
E/AndroidRuntime(15657):    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
E/AndroidRuntime(15657):    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
E/AndroidRuntime(15657):    at android.app.Activity.dispatchActivityResult(Activity.java:6274)
E/AndroidRuntime(15657):    at android.app.ActivityThread.deliverResults(ActivityThread.java:3614)
E/AndroidRuntime(15657):    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3661)
E/AndroidRuntime(15657):    at android.app.ActivityThread.access$1400(ActivityThread.java:155)
E/AndroidRuntime(15657):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1372)
E/AndroidRuntime(15657):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(15657):    at android.os.Looper.loop(Looper.java:139)
E/AndroidRuntime(15657):    at android.app.ActivityThread.main(ActivityThread.java:5298)
E/AndroidRuntime(15657):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15657):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15657):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
E/AndroidRuntime(15657):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
D/AppTracker(15657): App Event: crash
W/ActivityManager(  893):   Force finishing activity 1 com.awesomeproject/.MainActivity
W/ActivityManager(  893):  Dismiss app error dialog : com.awesomeproject
I/Process (15657): Sending signal. PID: 15657 SIG: 9
I/WindowState(  893): WIN DEATH: Window{2999a4f4 u0 com.awesomeproject/io.card.payment.DataEntryActivity}
I/ActivityManager(  893): Process com.awesomeproject (pid 15657) has died
I/WindowState(  893): WIN DEATH: Window{30d49a2c u0 com.awesomeproject/io.card.payment.CardIOActivity}
W/WindowManager(  893): Force-removing child win Window{27a5ca8a u0 SurfaceView} from container Window{30d49a2c u0 com.awesomeproject/io.card.payment.CardIOActivity}
W/WindowManager(  893): Failed looking up window
W/WindowManager(  893): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@3b873cf5 does not exist
W/WindowManager(  893):     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8734)
W/WindowManager(  893):     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8725)
W/WindowManager(  893):     at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1149)
W/WindowManager(  893):     at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState(  893): WIN DEATH: null
```

```
```

**Comment by jaypatel512** [comment] 2016-09-23 17:50
Hey @Rart3001 !

I was not able to reproduce the issue you are seeing here. I was able to use the sampleApp to bring up the UI, and complete the flow. I am running this in Mac OSX.

Please make sure your npm dependencies are up to date, and you have not manually made any changes to the sample app.
<img width="1569" alt="screen shot 2016-09-23 at 12 45 21 pm" src="https://cloud.githubusercontent.com/assets/1309895/18795877/3461f100-818c-11e6-95ad-6511b4ff16c7.png">

**Comment by Rart3001** [comment] 2016-09-29 15:19
Hello @jaypatel512, I am developing in ubuntu with version 24 of the android sdk I think the issue is regarding versions of android, and I did work now, I send my solution in a pull request for you to review, greetings.

**Comment by jaypatel512** [comment] 2016-09-29 20:20
Closing this issue in favor of the PR.

**Closed as completed by jaypatel512** 2016-09-29 20:20 UTC
